server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: http://catalog:8080
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: inventory
          uri: http://inventory:8080
          predicates:
            - Path=/inventory/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info

